spring:

  application:
    name: tubelens

  elasticsearch:
    uris: http://localhost:9200/

  datasource:
    url: jdbc:mysql://localhost:3306/tubelens?serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

youtube:
  api:
    key:

server:
  port: 8080